// AUTO-GENERATED by latensor — do not edit.
//
// Wrapper that replaces a polly-detected SCoP function with a call into a
// tuned TVM kernel loaded from a shared library. Linked with the original
// .o (whose original symbol has been redefined to <fn>__orig via objcopy)
// so the linker picks this strong definition.
//
// Lifetime: the TVM module + function are held in function-static slots,
// initialized on first call. The Module is intentionally leaked (allocated
// via `new`) to avoid relying on TVM runtime globals still being alive at
// process-exit static-destruction time.

#include <tvm/ffi/extra/module.h>
#include <tvm/runtime/tensor.h>

extern "C" void reduction_1(const float* A, float* B, float* T, [[maybe_unused]] int N) {
    static auto* __latensor_mod = new tvm::ffi::Module(
        tvm::ffi::Module::LoadFromFile("/home/bhavya/cosmos/life/UIUC/academics/coursework/CS526/latensor/src/tests/reduction_1/build_dir/tvm_libs/reduction_1.so"));
    static auto __latensor_fn =
        (*__latensor_mod)->GetFunction("main").value();

    static int64_t __shape_A[1] = { 2000000 };
    DLTensor __dl_A;
    __dl_A.data = const_cast<void*>(static_cast<const void*>(A));
    __dl_A.device = { kDLCPU, 0 };
    __dl_A.ndim = 1;
    __dl_A.dtype = { kDLFloat, 32, 1 };
    __dl_A.shape = __shape_A;
    __dl_A.strides = nullptr;
    __dl_A.byte_offset = 0;

    static int64_t __shape_B[1] = { 1 };
    DLTensor __dl_B;
    __dl_B.data = const_cast<void*>(static_cast<const void*>(B));
    __dl_B.device = { kDLCPU, 0 };
    __dl_B.ndim = 1;
    __dl_B.dtype = { kDLFloat, 32, 1 };
    __dl_B.shape = __shape_B;
    __dl_B.strides = nullptr;
    __dl_B.byte_offset = 0;

    __latensor_fn(&__dl_A, &__dl_B);
}
